export const strings = {
  enterPromptTitle: "Enter Your Prompt",
  surpriseMe: "Surprise me",
  placeholderText: "Ex. A blue lion logo reading ‘HEXA’ in bold letters",
  logoStylesTitle: "Logo Styles",
  promptLabel: "Prompt",
  copy: "Copy",
  monogramStyle: "Monogram",
  noStyle: "No Style",
  abstractStyle: "Abstract",
  mascotStyle: "Mascot",
  aiLogoHeader: "AI Logo",
  yourDesignHeader: "Your Design",
  creatingDesign: "Creating Your Design...",
  readyInTwoMinutes: "Ready in 2 minutes",
  errorTitle: "Oops, something went wrong!",
  errorSubtitle: "Click to try again.",
  successTitle: "Your Design is Ready!",
  successSubtitle: "Tap to see it.",
};
